#version: ""
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: parking-history
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - parking-network

  postgres16:
    container_name: postgres16
    image: postgres:16.2-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: parking-detail
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-pgsql:/var/lib/postgresql/data
    restart: always
    networks:
      - parking-network

  driver-parking-detail-service:
    container_name: driver-parking-detail-service
    image: driver-parking-detail-image:latest
    #image: yaayho/driver-parking-detail-image
    build:
      tags:
        - driver-parking-detail-image:latest
        - yaayho/driver-parking-detail-image
      context: ./
      dockerfile: ./driver-parking-detail-service/Dockerfile
    ports:
      - "8012:8012"
    env_file: ./driver-parking-detail-service/.env
    networks:
      - parking-network
    depends_on:
      - mysql8

  driver-parking-history-service:
    container_name: driver-parking-history-service
    image: driver-parking-history-image:latest
    #image: yaayho/driver-parking-history-image
    build:
      tags:
        - driver-parking-history-image:latest
        - yaayho/driver-parking-history-image
      context: ./
      dockerfile: ./driver-parking-history-service/Dockerfile
    ports:
      - "8011:8011"
    env_file: ./driver-parking-history-service/.env
    networks:
      - parking-network
    depends_on:
      - postgres16

volumes:
  data-mysql:
    name: data-mysql
  data-pgsql:
    name: data-pgsql

networks:
  parking-network:
    name: parking-network
    external: true