apiVersion: v1
kind: Service
metadata:
  name: driver-parking-detail
spec:
  ports:
  - port: 8012
    protocol: TCP
    targetPort: 8012
  selector:
    app: driver-parking-detail
  type: LoadBalancer