apiVersion: v1
kind: Service
metadata:
  name: driver-parking-history
spec:
  ports:
  - port: 8011
    protocol: TCP
    targetPort: 8011
  selector:
    app: driver-parking-history
  type: LoadBalancer